### ISSUE TITLE
Use password prompt for signin

### ISSUE THREAD

**Issue by creasty** [argon/mas#14]
It's a terrible design for passing raw password as an argument.
Your password will be stored in .bash_history.
Use `read -s` instead.

> To sign into the Mac App Store for the first time run mas signin.
>
```
$ mas signin mas@example.com "ZdkM4f$gzF;gX3ABXNLf8KcCt.x.np"
==> Signing in to Apple ID: mas@example.com
```

**Comment by argon** [comment]
As stated in the README this project is designed first-and-foremost for scripting where supplying passwords as a parameter is the simplest solution. You are correct that this is not ideal but it was also the simplest to implement.

I am happy to review Pull Requests.

**Comment by bryanl** [comment]
@creasty it will store in history, and you can get around that by prepending a space before the command. 

http://stackoverflow.com/questions/6475524/how-to-prevent-commands-to-show-up-in-bash-history

**Comment by timsutton** [comment]
Also when scripting, it'd be common to be substituting in the password using an environment variable.

**Comment by booch** [comment]
Here's a good work-around to prompt for the username and password:

~~~ shell
mas signout \
  && mas signin \
    $(read -p "App Store Login: " MAS_LOGIN && echo $MAS_LOGIN) \
    $(read -s -p "App Store Password: " MAS_PASSWORD && echo $MAS_PASSWORD && echo) \
  || echo "Mac App Store login failed"
~~~

I had to add the `mas signout` because `mas signin` will return an error if you're already logged in. It might be better to just use `mas account` to check whether you're logged in first.
