### ISSUE TITLE
mas and tmux

### ISSUE THREAD

**Issue by trudheim** [argon/mas#16]
This isn't a bugreport as much as a "hey, look what I found".

If I ssh in to a remote mac (as an admin-enabled user), I can install and run mas, signin and list applications. If I on the other hand start a tmux session and try running mas there, I get errors like this:

    $ mas list
    Illegal instruction: 4
    $ mas account
    Not signed in
    $ mas signin user@domain.com "<password>"
    ==> Signing in to Apple ID: user@domain.com
    The operation couldn’t be completed. (MASErrorDomain error 6.)
    $ 

Outside of tmux, things work fine. I've not been able to work out what differs between the regular ssh environment and the tmux one, but something happens with tmux that prevents mas from working properly.

**Comment by trudheim** [comment]
OSX 10.11.4, mas 1.1.3, latest XCode etc.

**Comment by argon** [comment]
This is probably a permissions issue with tmux spawning the process with the wrong permissions for the necessary XPC. I'm pretty sure it needs to be run within some kind of graphical environment. I'll investigate this more when I can.

**Comment by argon** [comment]
This is a user namespace issue. It is similar to the issues with using `pbcopy` and `pbpaste` inside tmux.

The workaround for now is to `brew install reattach-to-user-namespace` then run `mas` with that utility.

```
$ tmux
$ reattach-to-user-namespace mas install
```

I'm going to keep this issue around because I'd like to investigate this further but the workaround above should solve the problem.
